### ISSUE TITLE
Excessive CPU consumption

### ISSUE THREAD

**Issue by dales** [vincaslt/vscode-highlight-matching-tag#16]
After using it for a while my CPU gets maxed out until i kill the extension process

**Comment by vincaslt** [comment]
Your title says memory, but description says CPU... I cannot verify that, because CPU was frying for me in vscode too but I tried uninstalling the extension and it still did, so it was not related. In fact, It seems that many people experience Code Helper freezing and maxing out CPU usage lately, which indicates that may be something in the vscode itself.

**Comment by dales** [comment]
Sorry to be clear CPU reaches at 100%.

**Comment by vincaslt** [comment]
v0.5 did many performance improvements, so closing it now. If there are further problems, feel free to reopen the issue.
