### ISSUE TITLE
Enable for other file extensions (erb)

### ISSUE THREAD

**Issue by crispincornett** [vincaslt/vscode-highlight-matching-tag#59]
Is it possible to configure this extension to work with other file extensions?  I really like it for html and would like to get it working for `html.erb` file extensions.

I'm pretty new to VSCode so maybe there's a setting that I'm missing?

**Comment by KamasamaK** [comment]
There are no settings for including or excluding particular languages or file extensions. It just tries to work for every file.

**Comment by crispincornett** [comment]
I guess it does look like its trying to work.

Here's how it looks on a html snippet with the syntax set to "HTML":

![vscode_html](https://user-images.githubusercontent.com/1141004/48433269-f2f08f00-e733-11e8-8835-63d85757277a.gif)

And then here's how it behaves with the same html snippet, but with the syntax set to "html.erb" :

![vscode_erb](https://user-images.githubusercontent.com/1141004/48433419-4b279100-e734-11e8-9416-a6f5a7b230dd.gif)

As you can see it highlights all same tags (in this instance all `div`), not just the matching ones.

**Comment by vincaslt** [comment]
The extension works for every syntax, even plain text. In this case it is working fine, but either the default vscode selection highlight is interfering and masking the highlight, or some other extension is. Unfortunately, I was not yet able to disable interfering decorations from other extensions, and in fact I'm starting to thing that's not even supposed to be allowed anyway.

You could try to set:
` "editor.occurrencesHighlight": false` 
and see if it's satisfactory for you (you could find how to target specific extensions, say .erb with this setting). The downside is that you won't get this occurencesHighlighting in other code too.

You could also try to use some custom styling, instead of underline, for example background highlighting (see [here](https://github.com/vincaslt/vscode-highlight-matching-tag#custom-styling)).

Since there is no immediate issue with the extension and the quirk you're seeing is caused by some external extension or vscode itself, I have nothing to fix, close the issue if there are no further comments.

**Comment by crispincornett** [comment]
Yeah, that makes sense.  Seems like it is an API maybe VSCode is missing.

I took your advice and customized the styles and then disabled the `"editor.occurrencesHighlight"` for `html.erb`.

`
      "[html.erb]": {
        "editor.occurrencesHighlight": false
      }
`
That seems to work just fine as far as I can tell.

Thanks for the help!
